# Generated by Django 2.2.16 on 2021-10-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
