# Generated by Django 2.2.16 on 2021-10-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Информация о себе', max_length=500, verbose_name='О себе')),
                ('location', models.CharField(blank=True, help_text='Страна проживания', max_length=30, verbose_name='Местоположение')),
                ('birth_date', models.DateField(blank=True, help_text='Ваша дата рождения', null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, help_text='Ваша фотография', null=True, upload_to='avatars/', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
