# Generated by Django 2.2.16 on 2021-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=150, verbose_name='Сообщение'),
        ),
    ]
