# Generated by Django 2.2.16 on 2021-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211008_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=400, verbose_name='Сообщение'),
        ),
    ]
